function TrajectoriesObjectPointsImgPair01 = importfile_fixed_master_img(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   TRAJECTORIESOBJECTPOINTSIMGPAIR01 = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   TRAJECTORIESOBJECTPOINTSIMGPAIR01 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   TrajectoriesObjectPointsImgPair01 = importfile('Trajectories_ObjectPoints_ImgPair_0-1.dat', 6, 115);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2023/12/29 19:18:37

%% Initialize variables.
if nargin<=2
    startRow = 6;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10f%17f%12f%12f%17f%12f%17f%12f%17f%17f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
TrajectoriesObjectPointsImgPair01 = table(dataArray{1:end-1}, 'VariableNames', {'TrajectoryID','DXm','DYm','DZm','Dxpi','xDypi','xSdxpix','Sdypix','CC_Coeff','vmd'});

