function TrajectoriesObjectPointsImgPair01 = importfile_lower_icefall(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRAJECTORIESOBJECTPOINTSIMGPAIR01 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  TRAJECTORIESOBJECTPOINTSIMGPAIR01 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TrajectoriesObjectPointsImgPair01 = importfile("D:\JIRP\JIRP_TL\full_trial\output_lower_icefall\Trajectories_ObjectPoints_ImgPair_0-1.dat", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Dec-2023 20:45:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "  ";

% Specify column names and types
opts.VariableNames = ["Var1", "TrajectoryID", "dXm", "dYm", "dZm", "dxpix", "dypix", "sdxpix", "sdypix", "s0LSMgreyValue", "CC_Coeff", "usedPixel", "vmd"];
opts.SelectedVariableNames = ["TrajectoryID", "dXm", "dYm", "dZm", "dxpix", "dypix", "sdxpix", "sdypix", "s0LSMgreyValue", "CC_Coeff", "usedPixel", "vmd"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
TrajectoriesObjectPointsImgPair01 = readtable(filename, opts);

end